[MAIN] ===== Init Model(Opt: sgd) & Dataset =====
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
 1769472/94765736 [..............................] - ETA: 37s
Traceback (most recent call last):
  File "/home/gang/miniconda3/envs/fl/lib/python3.10/site-packages/keras/src/utils/data_utils.py", line 88, in urlretrieve
    fd.write(chunk)
OSError: [Errno 122] Disk quota exceeded
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/gang/dfl/main.py", line 57, in <module>
    model = define_model(args)
  File "/home/gang/dfl/Library/models.py", line 111, in define_model
    model = ResNet50(weights=weight, include_top=False, input_shape=input_shape)
  File "/home/gang/miniconda3/envs/fl/lib/python3.10/site-packages/keras/src/applications/resnet.py", line 521, in ResNet50
    return ResNet(
  File "/home/gang/miniconda3/envs/fl/lib/python3.10/site-packages/keras/src/applications/resnet.py", line 232, in ResNet
    weights_path = data_utils.get_file(
  File "/home/gang/miniconda3/envs/fl/lib/python3.10/site-packages/keras/src/utils/data_utils.py", line 347, in get_file
    urlretrieve(origin, fpath, DLProgbar())
  File "/home/gang/miniconda3/envs/fl/lib/python3.10/site-packages/keras/src/utils/data_utils.py", line 86, in urlretrieve
    with open(filename, "wb") as fd:
OSError: [Errno 122] Disk quota exceeded