
===== Init Model(Opt: sgd) & Dataset =====
Traceback (most recent call last):
  File "/home/gang/dfl/main.py", line 62, in <module>
    train_data, test_data = load_dataset(args.dataset)
  File "/home/gang/dfl/Library/datasets.py", line 55, in load_dataset
    x_train = tf.image.resize(x_train, [32, 32])  # if we want to resize
  File "/home/gang/miniconda3/envs/fl/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/gang/miniconda3/envs/fl/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.ResourceExhaustedError: {{function_node __wrapped__ResizeBilinear_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[60000,32,32,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ResizeBilinear] name: